name: Update iCloud calendar

on:
  schedule:
    - cron: "*/5 * * * *"  # toutes les 5 minutes
  workflow_dispatch:       # pour lancer manuellement si tu veux

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download iCloud ICS
        run: |
          curl -L "https://p149-caldav.icloud.com/published/2/MjAxMzUxNTc3NTkyMDEzNcr33mN1DGhEldXvug77KN0t9d1rebBleay0FCAjfVQLuIMQEM2Z-MHl8yNkiiJKBWwm3k4FQkJ6pFVfQRdCTIk" -o calendar.ics

      - name: Check if calendar.ics changed
        run: |
          if git diff --quiet calendar.ics; then
            echo "No changes in calendar.ics"
            echo "NO_CHANGES=true" >> $GITHUB_ENV
          else
            echo "Calendar changed"
            echo "NO_CHANGES=false" >> $GITHUB_ENV
          fi

      - name: Commit and push if changed
        if: env.NO_CHANGES == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add calendar.ics
          git commit -m "Update calendar.ics"
          git push
